### PR TITLE
Made config file compatible with newer brunch versions

### PR DESCRIPTION
**Pull request by peterwilli**
Hi,

Looking forward to use your skeleton for my JS API, had some issues with the newest brunch version, so I fixed it. Have a nice day!

### CODE REVIEW

**Comment by monokrome** [comment]
That is indeed a weird one. Can you tell me what version of brunch you built this against?

**Comment by peterwilli** [comment]
@monokrome 
My version:
mini-van-peter:Javascript Peter$ brunch -V
1.7.10

**Comment by monokrome** [comment]
Okay. This change seems appropriate.

Does it work on your machine for brunch v1.7.10? Also, do you know which stable brunch version supports this `watched` key? It would be important to also update the `package.json` so that the project's version matches the version of brunch that it was built for when changes are made.

Would you mind doing that so that I can test and merge this?

**Comment by peterwilli** [comment]
Hi @monokrome sure I'll check it out. I can confirm it works on my machine, I made the changes because I wanted to use brunch-for-libs.

I'll check out since which brunch `watched` is implemented and change the package.json accordingly.

**Comment by monokrome** [comment]
@peterwilli Any update here?

**Comment by peterwilli** [comment]
@monokrome Sorry was busy using your library in the weekend :+1: 

I just did some research, check this out: https://github.com/brunch/brunch/blob/master/CHANGELOG.md#brunch-170-23-july-2013

It says: "Added config.paths.watched which replaces config.paths.{app,test,vendor,assets}."

**Comment by peterwilli** [comment]
@monokrome so it must be since Brunch 1.7.0

**Comment by peterwilli** [comment]
@monokrome  Updated package :)

**Comment by monokrome** [comment]
Looks good, @peterwilli. Thank you for your contributions to the project!

**Pull request merged**
